import { groq } from "next-sanity";

export const homePageQuery = groq`
  *[_type == "homePage"][0]{
    title,
    galleryItems[]{
      _key,
      mediaType,
      orientation,
      image{
        alt,
        asset->
      },
      video{
        poster{
          asset->
        },
        mp4{
          asset->{
            url
          }
        },
        webm{
          asset->{
            url
          }
        }
      }
    }
  }
`;

export const fontsPageQuery = groq`
  *[_type == "fontsPage"][0]{
    title,
    navLinks[]{
      _key,
      label,
      url
    },
    introTitle,
    introText,
    columns{
      left[]{
        _key,
        size,
        marginTopVh,
        marginBottomVh,
        image{
          alt,
          asset->{
            url,
            metadata{
              dimensions{
                width,
                height
              }
            }
          }
        }
      },
      middle[]{
        _key,
        size,
        marginTopVh,
        marginBottomVh,
        image{
          alt,
          asset->{
            url,
            metadata{
              dimensions{
                width,
                height
              }
            }
          }
        }
      },
      right[]{
        _key,
        size,
        marginTopVh,
        marginBottomVh,
        image{
          alt,
          asset->{
            url,
            metadata{
              dimensions{
                width,
                height
              }
            }
          }
        }
      }
    }
  }
`;